mode = "dark"

accent               = "#33FF99"
selection            = "#0F3322"
muted                = "#1FAA66"
background           = "#050805"
dark_background      = "#030503"
darker_background    = "#000000"
lighter_background   = "#0B140E"
foreground           = "#33FF99"
dark_foreground      = "#1FAA66"
light_foreground     = "#88FFC0"
bright_foreground    = "#CCFFE6"
red                  = "#D4FF66"
yellow               = "#AAFF77"
orange               = "#C2FF70"
green                = "#33FF99"
cyan                 = "#55FFCC"
blue                 = "#44DDAA"
magenta              = "#88FFBB"
brown                = "#0F6640"
bright_red           = "#E6FF99"
bright_yellow        = "#CCFFAA"
bright_green         = "#88FFC0"
bright_cyan          = "#99FFE0"
bright_blue          = "#77EEC4"
bright_magenta       = "#B0FFD4"
selection_background = "#0F3322"
selection_foreground = "#CCFFE6"
